version: "3"

services:

  web_frontend:
    image: frontend
    ports:
      - "80:3000"

  web_comments:
    image: comments
    ports:
      - "3000:3000"
    links:
      - mongoDB
    depends_on:
      - mongoDB
  
  web_members:
    image: members
    ports:
      - "8080:3000"

  mongoDB:
    image: mongo
    ports:
      - "27017:27017"